name: anime_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Flutter & UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.1
  lottie: ^3.3.1
  flutter_slidable: ^4.0.1
  shimmer: ^3.0.0

  # Firebase
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1

  # State Management
  flutter_riverpod: ^3.0.0

  # สำหรับ Cloudinary + Image Picker
  cloudinary_public: ^0.23.1
  image_picker: ^0.8.7+4

  # Crypto สำหรับ SHA1 signature Cloudinary
  crypto: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/CamelCase.json
