// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw5MuL4JId_bhDtnSr0WaEa7QjjCiLTDc',
    appId: '1:699903741163:web:a1e5416992d75d2b6482ae',
    messagingSenderId: '699903741163',
    projectId: 'anime-app-project-cfe21',
    authDomain: 'anime-app-project-cfe21.firebaseapp.com',
    storageBucket: 'anime-app-project-cfe21.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNuKuSLTRas0woltjxuz0aYqls23wHhPc',
    appId: '1:699903741163:android:eea7e1163e4ae1666482ae',
    messagingSenderId: '699903741163',
    projectId: 'anime-app-project-cfe21',
    storageBucket: 'anime-app-project-cfe21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu2NFEC0bfRvKu5KRTxjW19yAse-LbHKs',
    appId: '1:699903741163:ios:67ee4ae3d24de5b06482ae',
    messagingSenderId: '699903741163',
    projectId: 'anime-app-project-cfe21',
    storageBucket: 'anime-app-project-cfe21.firebasestorage.app',
    iosBundleId: 'com.example.animeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu2NFEC0bfRvKu5KRTxjW19yAse-LbHKs',
    appId: '1:699903741163:ios:67ee4ae3d24de5b06482ae',
    messagingSenderId: '699903741163',
    projectId: 'anime-app-project-cfe21',
    storageBucket: 'anime-app-project-cfe21.firebasestorage.app',
    iosBundleId: 'com.example.animeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw5MuL4JId_bhDtnSr0WaEa7QjjCiLTDc',
    appId: '1:699903741163:web:bc901617e50807516482ae',
    messagingSenderId: '699903741163',
    projectId: 'anime-app-project-cfe21',
    authDomain: 'anime-app-project-cfe21.firebaseapp.com',
    storageBucket: 'anime-app-project-cfe21.firebasestorage.app',
  );
}
